=== VNeufeld/jboss-hsgw/jboss-hsgw-tool/oi/BookingResponse/BookingResponse.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- Mit XMLSpy v2007 sp2 (http://www.altova.com) von XMLSpy 2007 Professional Ed., Installed for 2 users (with SMP from 2006-12-12 to 2007-12-13) (BPCS GmbH) bearbeitet -->
<!-- edited with XMLSpy v2005 sp2 U (http://www.altova.com) by Stefan Holling (BPCS Consulting Services GmbH) -->
<!--W3C Schema generated by XMLSpy v2005 sp2 U (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Administration">
		<xs:annotation>
			<xs:documentation>Contains administrative data</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Errors" minOccurs="0"/>
				<xs:element ref="Error" minOccurs="0"/>
				<xs:element ref="BookStatus" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="BookStatus">
		<xs:annotation>
			<xs:documentation>Contains status related data</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Reason" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Reason">
		<xs:annotation>
			<xs:documentation>A reason why the status has been changed</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Id"/>
				<xs:element ref="Text"/>
				<xs:element ref="Status"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Id" type="xs:string">
		<xs:annotation>
			<xs:documentation>An id</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="Text" type="xs:string">
		<xs:annotation>
			<xs:documentation>A text</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="BookingId" type="xs:string">
		<xs:annotation>
			<xs:documentation>The booking id</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="CarPrice">
		<xs:annotation>
			<xs:documentation>The cars price</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{1,},\d{2}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Error">
		<xs:annotation>
			<xs:documentation>Contains an error</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ErrorType"/>
				<xs:element ref="ErrorText"/>
				<xs:element ref="ErrorNo"/>
				<xs:element ref="MessageText" minOccurs="0"/>
				<xs:element ref="MessageType" minOccurs="0"/>
				<xs:element ref="MessageNo" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MessageText" type="xs:string">
		<xs:annotation>
			<xs:documentation>The text of the business message</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="RateQualifier" type="xs:string">
		<xs:annotation>
			<xs:documentation>A sell reference from External Supplier</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="MessageType" type="xs:string">
		<xs:annotation>
			<xs:documentation>The type of the business message</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="MessageNo" type="xs:string">
		<xs:annotation>
			<xs:documentation>The number of the business message. See file MessageCodes.txt for a description</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="ErrorNo" type="xs:string">
		<xs:annotation>
			<xs:documentation>The number of the error. See file ErrorCodes.txt for a description</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="ErrorText" type="xs:string">
		<xs:annotation>
			<xs:documentation>The description of the error</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="ErrorType" type="xs:string">
		<xs:annotation>
			<xs:documentation>The type of the error</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="Errors">
		<xs:annotation>
			<xs:documentation>Contains error objects</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Error" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="RequestorResult">
		<xs:annotation>
			<xs:documentation>Enveloping tag</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Administration"/>
				<xs:element ref="Travel"/>
				<xs:element ref="Insurance" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="sessionId" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Travel">
		<xs:annotation>
			<xs:documentation>Contains travel related data</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="BookingId"/>
				<xs:element ref="CarPrice"/>
				<xs:element ref="Status"/>
				<xs:element ref="RateQualifier" minOccurs="0"/>
				<xs:element ref="Description" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Status">
		<xs:annotation>
			<xs:documentation>0 = on request, 1 = stop sale, 13 = available</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="0"/>
				<xs:enumeration value="1"/>
				<xs:enumeration value="13"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Description" type="xs:string">
		<xs:annotation>
			<xs:documentation>car description</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="Insurance">
		<xs:annotation>
			<xs:documentation>Information about insurance. IDs used: 1=CancelInsurance, 2=SCDW</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element ref="Id"/>
				<xs:element ref="Flag"/>
				<xs:element ref="Price"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="Flag" type="xs:int">
		<xs:annotation>
			<xs:documentation>Insurance flag ( always 1 )</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="Price">
		<xs:annotation>
			<xs:documentation>The price</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{1,},\d{2}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== VNeufeld/jboss-hsgw/jboss-hsgw-tool/oi/BookingResponse/BookingResponse.xml
<?xml version="1.0" encoding="UTF-8"?>
<RequestorResult id="0" sessionId="11132038798520" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BookingResponse.xsd">
	<Administration>
		<Errors>
		<Error>
			<ErrorType/>
			<ErrorText/>
			<ErrorNo/>
			<MessageText>INFO_STATUS_CHANGED</MessageText>
			<MessageType>2</MessageType>
			<MessageNo>629</MessageNo>
		</Error>
		</Errors>
		<BookStatus>
			<Reason>
				<Id>105</Id>
				<Text>Station: Ã–ffnungszeit Abgabe</Text>
				<Status>1</Status>
			</Reason>
			<Reason>
				<Id>106</Id>
				<Text>Supplier: One-Way</Text>
				<Status>0</Status>
			</Reason>
			<Reason>
				<Id>100</Id>
				<Text>Car: Stop/Free-Vereinbarung</Text>
				<Status>0</Status>
			</Reason>
		</BookStatus>
	</Administration>
	<Travel>
		<BookingId>0000197/01</BookingId>
		<CarPrice>121,59</CarPrice>
		<Status>13</Status>
		<RateQualifier>123478AGH8517856-7235</RateQualifier>
	</Travel>
	<Insurance>
	  <Price>210,00</Price>
	  <Id>1</Id>
	  <Flag>1</Flag>
	</Insurance>
</RequestorResult>
