=== VNeufeld/jboss-hsgw/jboss-hsgw-tool/oi/GetCarsRequest/GetCarsRequest.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- Mit XMLSpy v2007 sp2 (http://www.altova.com) von XMLSpy 2007 Professional Ed., Installed for 2 users (with SMP from 2006-12-12 to 2007-12-13) (BPCS GmbH) bearbeitet -->
<!-- edited with XMLSpy v2005 sp2 U (http://www.altova.com) by Stefan Holling (BPCS Consulting Services GmbH) -->
<!--W3C Schema generated by XMLSpy v2005 sp2 U (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="OutputConfiguration">
		<xs:annotation>
			<xs:documentation>Configuration for output format</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ErrorFormat" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ErrorFormat">
		<xs:annotation>
			<xs:documentation>A format for error in the response</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="multiple" type="xs:boolean">
						<xs:annotation>
							<xs:documentation>return multiple or singular error format</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Administration">
		<xs:annotation>
			<xs:documentation>Contains administrative data</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="UserType"/>
				<xs:element ref="LanguageId"/>
				<xs:element ref="OperatorId"/>
				<xs:choice>
					<xs:element ref="BrokerId" minOccurs="0"/>
					<xs:sequence minOccurs="0">
						<xs:element ref="AgencyId"/>
						<xs:element ref="MarkUpRel" minOccurs="0"/>
					</xs:sequence>
				</xs:choice>
				<xs:element ref="OutputConfiguration" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="BrokerId" type="xs:long">
		<xs:annotation>
			<xs:documentation>A broker id</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="AgencyId" type="xs:long">
		<xs:annotation>
			<xs:documentation>A agency id</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="MarkUpRel" type="xs:string">
		<xs:annotation>
			<xs:documentation>A agency markup</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="DropOffDate">
		<xs:annotation>
			<xs:documentation>The drop off date</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{4}-\d{2}-\d{2}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DropOffStationId" type="xs:long">
		<xs:annotation>
			<xs:documentation>The drop off station id</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="ServCatId" type="xs:long">
		<xs:annotation>
			<xs:documentation>The service catalog id</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="DropOffSupplierId" type="xs:long">
		<xs:annotation>
			<xs:documentation>The drop off supplier id</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="DropOffTime">
		<xs:annotation>
			<xs:documentation>The drop off time</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{2}:\d{2}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="LanguageId">
		<xs:annotation>
			<xs:documentation>The desired language in ISO-639</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="[a-z]{2}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="OperatorId" type="xs:long">
		<xs:annotation>
			<xs:documentation>The operator id</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="PartnerNo" type="xs:long">
		<xs:annotation>
			<xs:documentation>The partner number</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="PickUpDate">
		<xs:annotation>
			<xs:documentation>The pick up date</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{4}-\d{2}-\d{2}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="PickUpStationId" type="xs:long">
		<xs:annotation>
			<xs:documentation>The pick up station id</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="PickUpSupplierId" type="xs:long">
		<xs:annotation>
			<xs:documentation>The pick up supplier id</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="PickUpTime">
		<xs:annotation>
			<xs:documentation>The pick up time</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{2}:\d{2}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="PromoCode" type="xs:string">
		<xs:annotation>
			<xs:documentation>The promotion code</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="Request">
		<xs:annotation>
			<xs:documentation>Enveloping tag</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="CalledFrom"/>
				<xs:element ref="DemandedObjects"/>
				<xs:element ref="Administration"/>
				<xs:element ref="Travel"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Travel">
		<xs:annotation>
			<xs:documentation>Contains travel related data</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="PromoCode"/>
				<xs:element ref="ServCatId"/>
				<xs:element ref="PickUpDate"/>
				<xs:element ref="DropOffDate"/>
				<xs:element ref="PickUpTime"/>
				<xs:element ref="DropOffTime"/>
				<xs:element ref="PickUpStationId"/>
				<xs:element ref="DropOffStationId"/>
				<xs:element ref="PickUpSupplierId"/>
				<xs:element ref="DropOffSupplierId"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="UserType">
		<xs:annotation>
			<xs:documentation>Can be P for productive or T for test</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="P"/>
				<xs:enumeration value="T"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="RequestorRequest">
		<xs:annotation>
			<xs:documentation>Enveloping tag</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="RequestorName"/>
				<xs:element ref="RequestorRequestContent"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="RequestorName">
		<xs:annotation>
			<xs:documentation>Must be XML</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:attribute name="sessionId" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="RequestorRequestContent">
		<xs:annotation>
			<xs:documentation>Enveloping tag</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Request"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CalledFrom">
		<xs:annotation>
			<xs:documentation>Must be 5 for the web</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:short">
				<xs:enumeration value="5"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DemandedObjects">
		<xs:annotation>
			<xs:documentation>Contains DemandedObject objects</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DemandedObject"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DemandedObject">
		<xs:annotation>
			<xs:documentation>Must be 10002</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:short">
				<xs:enumeration value="10002"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== VNeufeld/jboss-hsgw/jboss-hsgw-tool/oi/GetCarsRequest/GetCarsRequest.xml
<?xml version="1.0" encoding="UTF-8"?>
<RequestorRequest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="GetCarsRequest.xsd">
	<RequestorName sessionId="">XML</RequestorName>
	<RequestorRequestContent>
		<Request>
			<CalledFrom>5</CalledFrom>
			<DemandedObjects>
				<DemandedObject>10002</DemandedObject>
			</DemandedObjects>
			<Administration>
				<UserType>P</UserType>
				<LanguageId>de</LanguageId>
				<OperatorId>1</OperatorId>
			</Administration>
			<Travel>
				<PromoCode/>
				<ServCatId>2</ServCatId>
				<PickUpDate>2008-09-26</PickUpDate>
				<DropOffDate>2008-09-29</DropOffDate>
				<PickUpTime>10:00</PickUpTime>
				<DropOffTime>10:00</DropOffTime>
				<PickUpStationId>547</PickUpStationId>
				<DropOffStationId>547</DropOffStationId>
				<PickUpSupplierId>6</PickUpSupplierId>
				<DropOffSupplierId>6</DropOffSupplierId>
			</Travel>
		</Request>
	</RequestorRequestContent>
</RequestorRequest>
